# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66d951974c23dd70bbca1c9a98aa858c4d3c998fc9fd9abe5169f4aa989a2d463ef6bdbdfc953547d509b2b019018e7f41436061e9812f13e237cd011c0870f7

test:
  secret_key_base: 85d310794bde16f22ac25e2de7ac19efd2066489a836961dff971bddac2a5f9cc76a4731c85fc8b893d62b0aa3743043dbdd456481d3ef57e3d8b4e2be096abc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
