# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13af4cbf4efefe05d2e9ff9066da2e00da339faf5b608ec902e5b370a5e172c1129be466d9aa4694fb99faa9b4f6ee1fd7f0a1a7fc9c65bab32a5ee899cc9c59

test:
  secret_key_base: 86493404ebbd3d5b856a0b9d5af0e5293f1d460cf8434d7ae09d603ef308907c469fca24a7c10d814b02fa44a042060d3090a909d68993df272214506948eec3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
