# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20b74e6280edfabbc8976c60e96062335e367f27cdbfd8421f3c631fffaf96795c0d7ba75a074b0816886dae845326f1c2b30f4656b02ad57a7135afb9d3f8d0

test:
  secret_key_base: 840403298649a4d550e10179e51354f65c4119bdee23d90442bf5b9366869f036ec33d434937121625bfacc1c8c69bcc537678ecfdbb9f1543c93321153de694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
