# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAppFolder', '0002_auto_20170419_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='User',
        ),
    ]
