# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAppFolder', '0003_auto_20170419_1241'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
