# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAppFolder', '0002_auto_20170417_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_print',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
