# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5fa81305873a299ec5ca94099a99102f2147b2b0917e6c14f0a58031fd81bcddd1bc409fd218af6fa2f70733dbd31d2dd46bdfa36a859e05cdfa15b2bb9bd22

test:
  secret_key_base: 869d72bf7261c75c8b11ccda2bd45d3f9518eeebbc9aed1bc424a4a37ec23b75bb3844a82ecd250059a08cd16777ed49f021f739bfdeb8b6dd695d63ae17a700

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
